apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookie-app

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: bookie-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.baraziza.online