apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mysql/mysql-deployment.yaml
  - mysql/mysql-service.yaml
  - bookie/bookie-deployment.yaml
  - bookie/bookie-service.yaml
  - ingress/ingress.yaml
  - ingress/storage-class.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd 