apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookie-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Baraziza/Bookie-GitOps
    targetRevision: HEAD
    path: k8s-manifests/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: bookie-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 